In [1]:
import pandas as pd
import seaborn as sns

In [8]:
import numpy as np
array_1d=np.array([1,2,3,4])
type(array_1d)
print(array_1d)


[1 2 3 4]


In [1]:
import pandas as pd

In [10]:
array_1d=np.array([2,3,5,6])
print(array_1d)

[2 3 5 6]


In [11]:
array=np.array([2,3,5,6,8,9,0])
print(array)

[2 3 5 6 8 9 0]


In [14]:
array=np.array([[1,2,3,4],[4,6,8,9]])
print(array)

[[1 2 3 4]
 [4 6 8 9]]


In [15]:
array=np.array([[1,3,5,7],[2,4,6,8]])
print(array)

[[1 3 5 7]
 [2 4 6 8]]


In [16]:
x=np.array([[[0,1,2,3],[4,5,6,7],[8,9,0,1]]])
print(x)

[[[0 1 2 3]
  [4 5 6 7]
  [8 9 0 1]]]


In [23]:
x=np.array([[[1,2,3,4,5],[5,6,7,8,9],[9,4,0,5,7]]])
print(x)

[[[1 2 3 4 5]
  [5 6 7 8 9]
  [9 4 0 5 7]]]


In [ ]:
arry1=[[[1, 2, 3 ,4 ,5]
array2=[5, 6 ,7 ,8, 9]
array3=[9, 4 ,0 ,5 ,7]]]
print[1:2]

In [26]:
x[0:0]

array([], shape=(0, 3, 5), dtype=int64)

In [ ]:
print